# This is a custom ROS 2 message definition.
# Each line defines one field, consisting of a type and a name.

string example_data


# Supported built-in data types:
# - bool
# - byte
# - char
# - float32
# - float64
# - int8
# - int16
# - int32
# - int64
# - string
# - uint8
# - uint16
# - uint32
# - uint64
# - wstring
#
# Any built-in type can be also defined as array, for example:
# - string[] (unbounded array)
# - string[5] (bounded, five string elements)
