controller_manager:
  ros__parameters:
    update_rate: 200 

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    blind_walk_controller:
      type: biped_control/BlindWalkController

/blind_walk_controller:
  ros__parameters:
    joints:
      - left_hip_pitch_joint
      - left_hip_roll_joint
      - left_knee_joint
      - right_hip_pitch_joint
      - right_hip_roll_joint
      - right_knee_joint
    
    
    initial_joint_positions: [0.3, 0.0, 0.6, -0.3, 0.0, -0.6]
    